[.Protocol]
# Todo: make scope usage
name = GenericTest

[Color<T>]
# The R channel
r = T
# The B channel
g = T
# The G channel
b = T

[Test]
# My 8bit color
color8 = Color<Int8>
# My 16bit color
color16 = Color<Int16>
